Bot testbed testbed (a testbed for a testbed) by Arseny

In [238]:
import numpy as np
import pandas as pd
from operator import itemgetter
from copy import deepcopy
import json

import draftsimtools as ds

In [239]:
# Load M19 drafts
raw_drafts = ds.load_drafts("../../data/m19_2.csv")

In [240]:
# Here other folks load card lists, but I grab them from json instead
# m19_set = ds.create_set("data/m19_rating.tsv", "data/m19_land_rating.tsv")

with open('../../data/Allsets.json', 'r',encoding='utf-8') as json_data:
    mtgJSON = json.load(json_data)
    
jsonSubset = mtgJSON['M19']['cards']

thisSet = {card['name'] : card for card in jsonSubset}

In [99]:
# thisSet[list(thisSet.keys())[0]] # Just to look at the fields

In [ ]:
# One (simple) way to create a list of names:
# nameList = pd.DataFrame(thisSet.keys(),columns = ['Name']) # Instead of relying on cvs, get names from json

In [242]:
# Another (fancier) way to create a list of names + lots of other useful stuff
nameList = pd.DataFrame.from_dict(thisSet, orient='index', columns=['colors','rarity','type','convertedManaCost'])
nameList['Name'] = a.index                 # We need names as a column, not an index
nameList['index'] = range(len(nameList))
nameList = nameList.set_index('index')     # And we need a normal numerical index
nameList[1:5]

colors    rarity                        type  convertedManaCost  \
index                                                                    
1         [R]    common                     Sorcery                3.0   
2         [W]  uncommon                     Instant                2.0   
3      [U, W]  uncommon  Creature — Human Artificer                4.0   
4         [U]  uncommon          Enchantment — Aura                2.0   

                       Name  
index                        
1            Act of Treason  
2      Aegis of the Heavens  
3           Aerial Engineer  
4             Aether Tunnel

In [243]:
# Process names, then handle weird card names (those with commas)

nameList['Name'] = nameList.Name.str.replace(' ','_')

# This utility method searches for "Name" column in nameList that have commas
nameList, raw_drafts = ds.fix_commas(nameList, raw_drafts) # Returns a tuple, as it updates both
# nameList.Name[nameList.Name.str.find(',')!=-1] # There should be no longer any cards with commas

In [244]:
# Process the drafts, deconstructing packs (hands) at every turn of every draft
drafts = ds.process_drafts(raw_drafts)

Processing draft: 0.
Processing draft: 10000.
Processing draft: 20000.
Processing draft: 30000.
Processing draft: 40000.
Processing draft: 50000.
Processing draft: 60000.
Processing draft: 70000.
Processing draft: 80000.
Processing draft: 90000.
Processing draft: 100000.


### Now this part below will just create bots and test them

In [245]:
# Splits into (toy) training and test sets. NOTE: For real training, use all drafts.
subset_drafts = drafts[5000:5500]
#train, test = train_test_split(subset_drafts, test_size = 0.4)

In [246]:
# nameList.Name = nameList.Name.str.lower()
nCardsInSet = len(nameList)
nCardsInSet

300

In [288]:
class bot_random(object):
    def __init__(self,nameList):
        self.nameList = nameList # a list with 'Name' column, containing the names
        
    def pickCard(self,longVector):
        nCards = int(len(longVector)/2)
        collection = longVector[0:nCards]
        pack = longVector[nCards:]
        cardInd = np.random.choice(np.nonzero(pack)[0])
        return cardInd

In [ ]:
# --- Naive bot (drafts like a 5-years-old) ----------TODO
class bot_color(object):
    def __init__(self,nameList):
        self.nameList = nameList # a list with 'Name' column, containing the names
        
    def pickCard(self,longVector):
        cardList = np.nonzero(hand)[0]
        cardInd = np.random.choice(listOfCards[self.thisSet(listOfCards)]NOT SURE WHAT TO DO)
        return cardInd

In [283]:
a = np.array(range(0,10))
b=5
print(a[0:b])
print(a[b:])
a[b+1:]

[0 1 2 3 4]
[5 6 7 8 9]


array([6, 7, 8, 9])

In [291]:
bot = bot_random(nameList)

# Count-hot encoding, then colling the bot
pickCount = 0
accuracySimple = 0

for iDraft in range(5): #range(len(subset_drafts)):
    draft = subset_drafts[iDraft]
    collection = np.zeros(nCardsInSet+1)
    for pack in draft:     
        packVector = np.zeros(nCardsInSet+1)
        iCard = 0
        for card in pack:
            cardName = card
            try:
                pos = nameList[nameList.Name==cardName].index[0]
            except:
                pos = nCardsInSet # Use this very large number (300 for M19) if not found; for now
                print("---Unrecognized card: ",cardName) # All unrecognized cards here seem to be foil lands
                #  	colors 	rarity 	type 	convertedManaCost 	Name
                nameList.append({[],'weird','weird',0,cardName})
                # ------------ TODOING here right now
                # ----- Make it add new cards to the list
            packVector[pos] += 1 # Mark the card
            
            if card==pack[0]: # First card, the one that was picked
                humanCard = pos
                
        # ----- that's where the bot should be called, with current collection and pack
        possibleCards = np.nonzero(packVector)[0]
        # possibleCards = possibleCards[possibleCards<nCardsInSet] # Remove unrecognized cards
        # print(nameList.iloc[possibleCards].colors)
        # condition = list('W' in color for color in nameList.iloc[possibleCards].colors)
        # possibleCards = possibleCards[condition]
        # print(condition)
        
        # botCard = listOfCards[0]
        botCard = bot.pickCard(np.concatenate([collection, packVector]))
        print(len(pack),botCard, humanCard==botCard)
        
        pickCount += 1
        if(humanCard==botCard):
            accuracySimple += 1 # Simple count of picked cards
        
        collection[humanCard] += 1 # Update collection
        
print("Simple accuracy: %4.2f" % (accuracySimple/pickCount))

---Unrecognized card:  Forest_3


TypeError: unhashable type: 'list'

In [228]:
possible = np.array([3,5,15,28])
# nameList.iloc[possible].rarity.str[0]=='u' # A good stub to work with rarity
print(nameList.iloc[possible].colors)

condition = list('W' in color for color in nameList.iloc[possible].colors)
print(condition)

possible[condition]

index
3     [U, W]
5        [W]
15        []
28       [R]
Name: colors, dtype: object
[True, True, False, False]


array([3, 5])

In [269]:
a = np.array([1,2,3])
b = np.array([4,5])
np.concatenate([a,b])

array([1, 2, 3, 4, 5])

In [ ]:
# Gets bot accuracy for some packs
tester = ds.BotTester(test)
tester.evaluate_bots([draftsim_bot, sgd_bot], ["Draftsim2018", "Draftsim2018SGD"])
tester.write_evaluations()