# Getting Started with Draftsim Bots
August 3, 2019

Make sure that you use the latest version of draftsimtools from MTG/Dan/draftsimtools. 

In [2]:
# You may have to install torch.
!pip install torch

You are using pip version 19.0.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import draftsimtools as ds
import numpy as np

### Load Data

In [4]:
# Define paths to dataset. 
# Can be downloaded from private "draft-data-files" channel on slack.
rating_path1 = "data/m19_rating.tsv"
rating_path2 = "data/m19_land_rating.tsv"
train_csv = "data/subset3000/train.csv"
val_csv = "data/subset3000/val.csv"

# Load data (may take a few moments).
train_data, train_tensor, m19_set, le = ds.load_dataset(rating_path1, rating_path2, "data/subset3000/train.csv")
val_data, val_tensor, m19_set, le = ds.load_dataset(rating_path1, rating_path2, "data/subset3000/val.csv")

Processing draft: 0.
Processing draft: 0.


### Label encoder
Maps card names to integers

In [5]:
le.transform(["Abnormal_Endurance", "Act_of_Treason"])

array([0, 1])

In [6]:
le.classes_[:20]

array(['Abnormal_Endurance', 'Act_of_Treason', 'Aegis_of_the_Heavens',
       'Aerial_Engineer', 'Aether_Tunnel', 'Aethershield_Artificer',
       "Ajani's_Last_Stand", "Ajani's_Pridemate", "Ajani's_Welcome",
       'Ajani_Adversary_of_Tyrants', 'Alpine_Moon',
       'Amulet_of_Safekeeping', 'Angel_of_the_Dawn', 'Anticipate',
       'Apex_of_Power', 'Arcades_the_Strategist', 'Arcane_Encyclopedia',
       'Aven_Wind_Mage', 'Aviation_Pioneer', 'Banefire'], dtype=object)

### Draft Dataset
Pick data is contained in a draft dataset. Data can be accessed via a simple index.

In [7]:
x, y = train_data[10]

### Input Representation
x is a vector of length 2n, where n is the number of cards in the set.  

x[:n] represent the counts of cards already picked by the user.  
x[n:2n] represent the cards in the current pack (1 if card is present in pack). 

In [8]:
print(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 

### Output Representation
y is a vector of length n
y[i]=1, where i is the index of the card picked by the user.

In [9]:
print(y)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Numpy Conversion
By default, x and y are torch tensors. You may want to convert them to numpy arrays. 

In [10]:
print("y:", type(y))
y_numpy = y.numpy()
print("y_numpy:", type(y_numpy))

y: <class 'torch.Tensor'>
y_numpy: <class 'numpy.ndarray'>


### Set Dataframe
Contains information about each card in the set. It may be useful if you would like to include features like color and converted mana cost. 

In [29]:
m19_set.head()

Name Casting Cost 1 Casting Cost 2     Card Type Rarity  \
0       Crucible_of_Worlds              3           none         Spell      M   
1  Nicol_Bolas_the_Ravager           1UBR           none      Creature      M   
2               Scapeshift            2GG           none         Spell      M   
3        Sarkhan_Fireblood            1RR           none  Planeswalker      M   
4        Resplendent_Angel            1WW           none      Creature      M   

   Rating     Color Vector  
0     1.5  [0, 0, 0, 0, 0]  
1     4.6  [0, 1, 1, 1, 0]  
2     1.5  [0, 0, 0, 0, 2]  
3     3.3  [0, 0, 0, 2, 0]  
4     4.3  [2, 0, 0, 0, 0]

If you need it, an <b>intermediate</b> representation of a draft is available in train_tensor. 

### Intermediate Draft Representation
The above representation of x and y will work best for most models. If needed, however, a more compact representation of a draft is available in train_tensor.

Each row represents cards present in a pack seen by the user.  
The leftmost column represents the card picked.  

In [47]:
# Uncomment to view intermediate representation.
print(train_tensor[0,:,:])

[[212   7  37 207 181 226 146 259  73 198 252  17 144 114 126]
 [ 92 274 238 108 148  26 266 259 151  79 114 261 268 281   0]
 [ 89  69  97  79 216 253  33  62 268 190  23 155 165   0   0]
 [ 92 207 210 149 155 135 157 252  96  29 230  84   0   0   0]
 [ 77 108 112 273 193 146 267 262 260  35 232   0   0   0   0]
 [231  87 170  79 144 101 267   0 281 258   0   0   0   0   0]
 [ 92  31  75  39  43 114 118 252 187   0   0   0   0   0   0]
 [262 273 208 253 131 281  96 163   0   0   0   0   0   0   0]
 [ 73 198 252  17 144 114 126   0   0   0   0   0   0   0   0]
 [151  79 114 261 268 281   0   0   0   0   0   0   0   0   0]
 [268 190  23 155 165   0   0   0   0   0   0   0   0   0   0]
 [ 96  29 230  84   0   0   0   0   0   0   0   0   0   0   0]
 [260  35 232   0   0   0   0   0   0   0   0   0   0   0   0]
 [281 258   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [187   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [156  54  12 233  60  58  20  27  77 259  33  57  79 2

### A Very Simple Bot

In [12]:
class ActOfTreasonBot(object):
    
    def make_pick(self, x):
        """
        Input x is of length 2n and represents collection and pack.
        Returns y, a vector of length n that corresponds to the card picked.
        
        Every bot must implement this method.
        """
        # Always predict act of treason.
        act_of_treason = np.zeros(285)
        act_of_treason[1] = 1
        return act_of_treason

### Benchmark Validation Accuracy

In [13]:
# Create bot.
bot = ActOfTreasonBot()

#Initialize metrics.
num_correct = 0
num_picks = len(val_data)

# Count correct picks.
for pick in range(num_picks):
    x_torch, y_torch = train_data[pick]
    x = x_torch.numpy()
    y = y_torch.numpy()
    if np.argmax(bot.make_pick(x)) == np.argmax(y):
        num_correct += 1
        
val_accuracy = num_correct / (num_picks * 1.0)
print("Validation accuracy of ", val_accuracy)    

Validation accuracy of  0.007288888888888889
